name: deploy

on: workflow_dispatch

env:
  DOCKER_IMAGE: resume-rita
  VERSION: '1.0'
  TARGET_FOLDER: images

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: define build version
        id: default-version
        run: echo "TAG_VERSION=${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: build docker
        id: build-docker
        run: docker build --load -t"${{env.DOCKER_IMAGE}}:${{env.VERSION}}.${{env.TAG_VERSION}}" .

      - name: stop old container if exist
        run: |
          docker stop "${{env.DOCKER_IMAGE}}" || true
          docker rm "${{env.DOCKER_IMAGE}}" || true

      - name: deploy
        id: deploy
        run: docker run -d --network main_network --restart unless-stopped --name ${{env.DOCKER_IMAGE}} -p 3002:3000 ${{env.DOCKER_IMAGE}}:${{env.VERSION}}.${{env.TAG_VERSION}}
